# Generated by Django 4.2.1 on 2024-08-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="minute_when_newsletter_should_sent",
            field=models.PositiveIntegerField(
                verbose_name="минута, в которую нужно отправить сообщение, например 01 или 60"
            ),
        ),
    ]
